# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b221dff7a41737f3ee0d0f886e4491e53be2570e57d7d424d8b19afae109fc97799012789cfc01a47e1a77209d5f4d72334eef17d8dbf03430a3a4d27d5441f

test:
  secret_key_base: 89e60f9c75fa846c8a20573d1c9a9651a5df59f5e621342c17f8d5822fd741d1068304deb9d0d577c853d2b2b1c212af7c9a95e2845b31858c1dbb9631570403

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
